version: "3.7"
services:
  app:
    build:
      args:
        user: php8
        uid: 1000
      context: ./docker/php8/
      dockerfile: Dockerfile
    image: php8
    container_name: php8-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network
  
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx-app
    restart: unless-stopped
    ports:
      - 8089:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
