version: "3.7"
services:
  app:
    build:
      args:
        user: php
        uid: 1000
      context: ./docker/php/
      dockerfile: Dockerfile
    image: laracmsphp
    container_name: php-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network

  node:
    build:
      args:
        user: node
        uid: 1000
      context: ./docker/node/
      dockerfile: Dockerfile
    image: laracmsnode
    container_name: node-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network
  
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx-app
    restart: unless-stopped
    ports:
      - 8089:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db-app
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
